_core:
  default_config_hash: RIxOrFfayh9I8CHci50AVKpNXA7KzkTLnjATp5-xW5A
ignored_bundles:
  node:
    - article
  paragraph:
    - ignored_paragraph_bundle
ignored_fields:
  node:
    - field_regression_ignored
  paragraph:
    - field_regression_ignored
