extends:
  - "@reloaddk/stylelint-recommended-scss"
rules:
  no-descending-specificity: null
  no-invalid-position-at-import-rule: null
  selector-max-compound-selectors: null
  max-nesting-depth: null
  selector-no-qualifying-type: null
  color-named: null
  declaration-empty-line-before: null
  property-no-vendor-prefix: null
  value-no-vendor-prefix: null
  selector-max-id: null
  scss/at-mixin-pattern: "^[a-z_][a-z0-9_-]*$"
  scss/dollar-variable-pattern: "^[a-z_][a-z0-9_-]*$"
  scss/percent-placeholder-pattern: "^[a-z_][a-z0-9_-]*$"
  selector-class-pattern: "[A-Za-z0-9_-]+"
