#!/usr/bin/env bash

##
# Install a Drupal cron file in /etc/cron.d
#
# We use this script to generate and write the cron file to make sure
# owership and permissions are as required by cron(8).
#
# The cron job is executed every ten minutes ("*/10 * * * *"). You can
# specify another interval using the `DRUPAL_CRON_TIME` environment
# variable.

set -euo pipefail
IFS=$'\n\t'

FILENAME=drupal-cron
TMPDIR=$(mktemp -d)

cleanup() {
    rm -rf "${TMPDIR}"
}

trap cleanup EXIT

# Function that writes actual cron file content to stdout.
function croncontent {
    cat <<EOF
# Code generated by $(realpath "$0"). DO NOT EDIT.
${DRUPAL_CRON_TIME-"*/10 * * * *"} root (. /etc/container_environment.sh && cd /var/www/web && /var/www/vendor/bin/drush core:cron) 2>&1 | /usr/bin/logger -t cron
EOF
}

# Create a temporary cron file.
croncontent > "${TMPDIR}/${FILENAME}"

# Make sure it has ownership and permissions as required by cron(8).
chown root "${TMPDIR}/${FILENAME}"
chmod og-w "${TMPDIR}/${FILENAME}"

# Move temporary cron file into actual location.
mv "${TMPDIR}/${FILENAME}" "/etc/cron.d/${FILENAME}"
