name: 'Drupal Regression'

on: pull_request
permissions: write-all

jobs:
  drupal-regression:
    uses: reload/action-drupal-regression/.github/workflows/drupal-regression.yml@main
    with:
      PLATFORMSH_ID: ndwh3lq2xnuyg
    secrets:
      PLATFORMSH_KEY: ${{ secrets.DAIS_PLATFORMSH_KEY }}
