on: pull_request

name: Drupal Check
jobs:
  drupal-check:
    name: Check and report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: gd, intl
        coverage: none
    - name: Install composer dependencies
      run: |
        composer install --no-interaction --no-progress
    - name: Deprecations check and report
      uses: reload/drupal-check-reviewdog-action@master
      with:
        check: deprecations
        paths: |-
          web/modules/custom
          web/themes/custom
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Analysis check and report
      uses: reload/drupal-check-reviewdog-action@master
      with:
        check: analysis
        paths: |-
          web/modules/custom
          web/themes/custom
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
