on: pull_request
name: JavaScript
jobs:

  # See https://github.com/reload/action-jsts-quality
  eslint-reviewdog:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./web/themes/custom/storypal_theme

      - name: JSTS Quality
        uses: reload/action-jsts-quality@main
        with:
          github_token: ${{ github.token }}
          working_directory: './web/themes/custom/storypal_theme'
          prettier_target: './src/js/**/*'
          eslint_target: './src/js'
