on: pull_request
name: PHP unit tests

jobs:

  phpstan:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress
          # Add vendor/bin to PATH for subsequent steps, see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          composer config bin-dir --absolute >> "${GITHUB_PATH}"
      - name: Run PHPUnit
        run: |
          # `colors="true"` in phpunit.xml.dist is apparently
          # equivalent to --colors=auto, and phpunit seems to think
          # that colors isn't supported in GitHub action.
          phpunit --colors=always
