on: pull_request
name: SCSS
jobs:

  # See https://github.com/reload/action-style-quality
  stylelint-reviewdog:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./web/themes/custom/storypal_theme

      - name: Style Quality
        uses: reload/action-style-quality@main
        with:
          github_token: ${{ github.token }}
          working_directory: ./web/themes/custom/storypal_theme
          prettier_target: './src/scss/**/*'
          stylelint_target: './src/scss/**/*'
